export const CHANGE_INDIVIDUAL_TEAM_YEAR = 'CHANGE_INDIVIDUAL_TEAM_YEAR';
export const CHANGE_INDIVIDUAL_TEAM_SORT_BY = 'CHANGE_INDIVIDUAL_TEAM_SORT_BY';
export const SET_INDIVIDUAL_TEAM_STATS = 'SET_INDIVIDUAL_TEAM_STATS';